services:
  mongodb:
    image: mongo:6.0
    container_name: url_shortener_mongodb
    ports:
      - "27017:27017" # Expondo a porta para acesso local (opcional)
    networks:
      - url_shortener_network
    volumes:
      - mongodb_data:/data/db # Persistência dos dados no host

  redis:
    image: redis:7
    container_name: url_shortener_redis
    ports:
      - "6379:6379" # Expondo a porta para acesso local (opcional)
    networks:
      - url_shortener_network

networks:
  url_shortener_network:
    driver: bridge

volumes:
  mongodb_data: